from django.db import models

# Create your models here.
# class summoner(models.Model):
#     summonerName = models.CharField(max_length=16)

#     def __str__(self):
#         return self.summonerName

# class spectatorInfo(models.Model):
#     RANK_CHOICES = (
#         ('UNRANKED', 'UNRANKED'),
#         ('IRON IV', 'IRON IV'),
#         ('IRON III', 'IRON III'),
#         ('IRON II', 'IRON II'),
#         ('IRON I', 'IRON I'),
#         ('BRONZE IV', 'BRONZE IV'),
#         ('BRONZE III', 'BRONZE III'),
#         ('BRONZE II', 'BRONZE II'),
#         ('BRONZE I', 'BRONZE I'),
#         ('SILVER IV', 'SILVER IV'),
#         ('SILVER III', 'SILVER III'),
#         ('SILVER II', 'SILVER II'),
#         ('SILVER I', 'SILVER I'),
#         ('GOLD IV', 'GOLD IV'),
#         ('GOLD III', 'GOLD III'),
#         ('GOLD II', 'GOLD II'),
#         ('GOLD I', 'GOLD I'),
#         ('PLATINUM IV', 'PLATINUM IV'),
#         ('PLATINUM III', 'PLATINUM III'),
#         ('PLATINUM II', 'PLATINUM II'),
#         ('PLATINUM I', 'PLATINUM I'),
#         ('DIAMOND IV', 'DIAMOND IV'),
#         ('DIAMOND III', 'DIAMOND III'),
#         ('DIAMOND II', 'DIAMOND II'),
#         ('DIAMOND I', 'DIAMOND I'),
#         ('MASTER I', 'MASTER I'),
#         ('GRANDMASTER I', 'GRANDMASTER I'),
#         ('CHALLENGER I', 'CHALLENGER I')
#     )

#     summonerName_1 = models.CharField(max_length=16)
#     summonerName_2 = models.CharField(max_length=16)
#     summonerName_3 = models.CharField(max_length=16)
#     summonerName_4 = models.CharField(max_length=16)
#     summonerName_5 = models.CharField(max_length=16)
#     summonerName_6 = models.CharField(max_length=16)
#     summonerName_7 = models.CharField(max_length=16)
#     summonerName_8 = models.CharField(max_length=16)
#     summonerName_9 = models.CharField(max_length=16)
#     summonerName_10 = models.CharField(max_length=16)
#     champName_1 = models.CharField(max_length=16)
#     champName_2 = models.CharField(max_length=16)
#     champName_3 = models.CharField(max_length=16)
#     champName_4 = models.CharField(max_length=16)
#     champName_5 = models.CharField(max_length=16)
#     champName_6 = models.CharField(max_length=16)
#     champName_7 = models.CharField(max_length=16)
#     champName_8 = models.CharField(max_length=16)
#     champName_9 = models.CharField(max_length=16)
#     champName_10 = models.CharField(max_length=16)
#     champ_1 = models.IntegerField(default=0)
#     champ_2 = models.IntegerField(default=0)
#     champ_3 = models.IntegerField(default=0)
#     champ_4 = models.IntegerField(default=0)
#     champ_5 = models.IntegerField(default=0)
#     champ_6 = models.IntegerField(default=0)
#     champ_7 = models.IntegerField(default=0)
#     champ_8 = models.IntegerField(default=0)
#     champ_9 = models.IntegerField(default=0)
#     champ_10 = models.IntegerField(default=0)
#     rank_1 = models.CharField(max_length=13, choices=RANK_CHOICES)
#     rank_2 = models.CharField(max_length=13, choices=RANK_CHOICES)
#     rank_3 = models.CharField(max_length=13, choices=RANK_CHOICES)
#     rank_4 = models.CharField(max_length=13, choices=RANK_CHOICES)
#     rank_5 = models.CharField(max_length=13, choices=RANK_CHOICES)
#     rank_6 = models.CharField(max_length=13, choices=RANK_CHOICES)
#     rank_7 = models.CharField(max_length=13, choices=RANK_CHOICES)
#     rank_8 = models.CharField(max_length=13, choices=RANK_CHOICES)
#     rank_9 = models.CharField(max_length=13, choices=RANK_CHOICES)
#     rank_10 = models.CharField(max_length=13, choices=RANK_CHOICES)
#     rankWins_1 = models.IntegerField(default=0)
#     rankWins_2 = models.IntegerField(default=0)
#     rankWins_3 = models.IntegerField(default=0)
#     rankWins_4 = models.IntegerField(default=0)
#     rankWins_5 = models.IntegerField(default=0)
#     rankWins_6 = models.IntegerField(default=0)
#     rankWins_7 = models.IntegerField(default=0)
#     rankWins_8 = models.IntegerField(default=0)
#     rankWins_9 = models.IntegerField(default=0)
#     rankWins_10 = models.IntegerField(default=0)
#     rankLosses_1 = models.IntegerField(default=0)
#     rankLosses_2 = models.IntegerField(default=0)
#     rankLosses_3 = models.IntegerField(default=0)
#     rankLosses_4 = models.IntegerField(default=0)
#     rankLosses_5 = models.IntegerField(default=0)
#     rankLosses_6 = models.IntegerField(default=0)
#     rankLosses_7 = models.IntegerField(default=0)
#     rankLosses_8 = models.IntegerField(default=0)
#     rankLosses_9 = models.IntegerField(default=0)
#     rankLosses_10 = models.IntegerField(default=0)
#     champPts_1 = models.BigIntegerField(default=-9999999)
#     champPts_2 = models.BigIntegerField(default=-9999999)
#     champPts_3 = models.BigIntegerField(default=-9999999)
#     champPts_4 = models.BigIntegerField(default=-9999999)
#     champPts_5 = models.BigIntegerField(default=-9999999)
#     champPts_6 = models.BigIntegerField(default=-9999999)
#     champPts_7 = models.BigIntegerField(default=-9999999)
#     champPts_8 = models.BigIntegerField(default=-9999999)
#     champPts_9 = models.BigIntegerField(default=-9999999)
#     champPts_10 = models.BigIntegerField(default=-9999999)
#     spell1Id_1 = models.IntegerField(default=0)
#     spell1Id_2 = models.IntegerField(default=0)
#     spell1Id_3 = models.IntegerField(default=0)
#     spell1Id_4 = models.IntegerField(default=0)
#     spell1Id_5 = models.IntegerField(default=0)
#     spell1Id_6 = models.IntegerField(default=0)
#     spell1Id_7 = models.IntegerField(default=0)
#     spell1Id_8 = models.IntegerField(default=0)
#     spell1Id_9 = models.IntegerField(default=0)
#     spell1Id_10 = models.IntegerField(default=0)
#     spell2Id_1 = models.IntegerField(default=0)
#     spell2Id_2 = models.IntegerField(default=0)
#     spell2Id_3 = models.IntegerField(default=0)
#     spell2Id_4 = models.IntegerField(default=0)
#     spell2Id_5 = models.IntegerField(default=0)
#     spell2Id_6 = models.IntegerField(default=0)
#     spell2Id_7 = models.IntegerField(default=0)
#     spell2Id_8 = models.IntegerField(default=0)
#     spell2Id_9 = models.IntegerField(default=0)
#     spell2Id_10 = models.IntegerField(default=0)
#     perk0_1 = models.IntegerField(default=0)
#     perk0_2 = models.IntegerField(default=0)
#     perk0_3 = models.IntegerField(default=0)
#     perk0_4 = models.IntegerField(default=0)
#     perk0_5 = models.IntegerField(default=0)
#     perk0_6 = models.IntegerField(default=0)
#     perk0_7 = models.IntegerField(default=0)
#     perk0_8 = models.IntegerField(default=0)
#     perk0_9 = models.IntegerField(default=0)
#     perk0_10 = models.IntegerField(default=0)
#     perk1_1 = models.IntegerField(default=0)
#     perk1_2 = models.IntegerField(default=0)
#     perk1_3 = models.IntegerField(default=0)
#     perk1_4 = models.IntegerField(default=0)
#     perk1_5 = models.IntegerField(default=0)
#     perk1_6 = models.IntegerField(default=0)
#     perk1_7 = models.IntegerField(default=0)
#     perk1_8 = models.IntegerField(default=0)
#     perk1_9 = models.IntegerField(default=0)
#     perk1_10 = models.IntegerField(default=0)
#     perk2_1 = models.IntegerField(default=0)
#     perk2_2 = models.IntegerField(default=0)
#     perk2_3 = models.IntegerField(default=0)
#     perk2_4 = models.IntegerField(default=0)
#     perk2_5 = models.IntegerField(default=0)
#     perk2_6 = models.IntegerField(default=0)
#     perk2_7 = models.IntegerField(default=0)
#     perk2_8 = models.IntegerField(default=0)
#     perk2_9 = models.IntegerField(default=0)
#     perk2_10 = models.IntegerField(default=0)
#     perk3_1 = models.IntegerField(default=0)
#     perk3_2 = models.IntegerField(default=0)
#     perk3_3 = models.IntegerField(default=0)
#     perk3_4 = models.IntegerField(default=0)
#     perk3_5 = models.IntegerField(default=0)
#     perk3_6 = models.IntegerField(default=0)
#     perk3_7 = models.IntegerField(default=0)
#     perk3_8 = models.IntegerField(default=0)
#     perk3_9 = models.IntegerField(default=0)
#     perk3_10 = models.IntegerField(default=0)
#     perk4_1 = models.IntegerField(default=0)
#     perk4_2 = models.IntegerField(default=0)
#     perk4_3 = models.IntegerField(default=0)
#     perk4_4 = models.IntegerField(default=0)
#     perk4_5 = models.IntegerField(default=0)
#     perk4_6 = models.IntegerField(default=0)
#     perk4_7 = models.IntegerField(default=0)
#     perk4_8 = models.IntegerField(default=0)
#     perk4_9 = models.IntegerField(default=0)
#     perk4_10 = models.IntegerField(default=0)
#     perk5_1 = models.IntegerField(default=0)
#     perk5_2 = models.IntegerField(default=0)
#     perk5_3 = models.IntegerField(default=0)
#     perk5_4 = models.IntegerField(default=0)
#     perk5_5 = models.IntegerField(default=0)
#     perk5_6 = models.IntegerField(default=0)
#     perk5_7 = models.IntegerField(default=0)
#     perk5_8 = models.IntegerField(default=0)
#     perk5_9 = models.IntegerField(default=0)
#     perk5_10 = models.IntegerField(default=0)
#     gameVersion = models.CharField(max_length=16)
#     primaryClass_1 = models.CharField(max_length=16)
#     secondaryClass_1 = models.CharField(max_length=16)
#     primaryClass_2 = models.CharField(max_length=16)
#     secondaryClass_2 = models.CharField(max_length=16)
#     primaryClass_3 = models.CharField(max_length=16)
#     secondaryClass_3 = models.CharField(max_length=16)
#     primaryClass_4 = models.CharField(max_length=16)
#     secondaryClass_4 = models.CharField(max_length=16)
#     primaryClass_5 = models.CharField(max_length=16)
#     secondaryClass_5 = models.CharField(max_length=16)
#     primaryClass_6 = models.CharField(max_length=16)
#     secondaryClass_6 = models.CharField(max_length=16)
#     primaryClass_7 = models.CharField(max_length=16)
#     secondaryClass_7 = models.CharField(max_length=16)
#     primaryClass_8 = models.CharField(max_length=16)
#     secondaryClass_8 = models.CharField(max_length=16)
#     primaryClass_9 = models.CharField(max_length=16)
#     secondaryClass_9 = models.CharField(max_length=16)
#     primaryClass_10 = models.CharField(max_length=16)
#     secondaryClass_10 = models.CharField(max_length=16)
#     rankWinRatio_1 = models.FloatField(null=False, blank=False, default=0.5)
#     rankWinRatio_2 = models.FloatField(null=False, blank=False, default=0.5)
#     rankWinRatio_3 = models.FloatField(null=False, blank=False, default=0.5)
#     rankWinRatio_4 = models.FloatField(null=False, blank=False, default=0.5)
#     rankWinRatio_5 = models.FloatField(null=False, blank=False, default=0.5)
#     rankWinRatio_6 = models.FloatField(null=False, blank=False, default=0.5)
#     rankWinRatio_7 = models.FloatField(null=False, blank=False, default=0.5)
#     rankWinRatio_8 = models.FloatField(null=False, blank=False, default=0.5)
#     rankWinRatio_9 = models.FloatField(null=False, blank=False, default=0.5)
#     rankWinRatio_10 = models.FloatField(null=False, blank=False, default=0.5)
#     avgRank1 = models.CharField(max_length=13, choices=RANK_CHOICES)
#     avgRank2 = models.CharField(max_length=13, choices=RANK_CHOICES)
#     avgRankWR1 = models.FloatField(null=False, blank=False, default=0.5)
#     avgRankWR2 = models.FloatField(null=False, blank=False, default=0.5)
#     avgChampMastery1 = models.BigIntegerField(default=-9999999)
#     avgChampMastery2 = models.BigIntegerField(default=-9999999)
#     champPts_rank_1 = models.BigIntegerField(default=-9999999)
#     champPts_rank_2 = models.BigIntegerField(default=-9999999)
#     champPts_rank_3 = models.BigIntegerField(default=-9999999)
#     champPts_rank_4 = models.BigIntegerField(default=-9999999)
#     champPts_rank_5 = models.BigIntegerField(default=-9999999)
#     champPts_rank_6 = models.BigIntegerField(default=-9999999)
#     champPts_rank_7 = models.BigIntegerField(default=-9999999)
#     champPts_rank_8 = models.BigIntegerField(default=-9999999)
#     champPts_rank_9 = models.BigIntegerField(default=-9999999)
#     champPts_rank_10 = models.BigIntegerField(default=-9999999)

#     def __str__(self):
#         return self.summonerName_1